import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, '..')
const mediaRoot = path.join(root, 'public', 'gallery-media')
const output = path.join(root, 'src', 'data', 'galleryMedia.generated.js')

const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif'])
const VIDEO_EXTENSIONS = new Set(['.mp4', '.webm', '.ogg', '.mov'])

function listMedia(folder, extensions) {
  const absolute = path.join(mediaRoot, folder)
  if (!fs.existsSync(absolute)) return []

  return fs.readdirSync(absolute)
    .filter(file => extensions.has(path.extname(file).toLowerCase()))
    .sort((a, b) => a.localeCompare(b))
    .map(file => ({
      title: path.basename(file, path.extname(file))
        .replace(/[_-]+/g, ' ')
        .replace(/\s+/g, ' ')
        .trim(),
      src: `/gallery-media/${folder}/${file}`,
    }))
}

const videos = listMedia('videos', VIDEO_EXTENSIONS)
const images = listMedia('images', IMAGE_EXTENSIONS)

const content = `// This file is generated by scripts/generate_gallery_manifest.js.
// Put files in public/gallery-media/images or public/gallery-media/videos,
// then run: npm run gallery:manifest

export const GALLERY_VIDEOS = ${JSON.stringify(videos, null, 2)}

export const GALLERY_IMAGES = ${JSON.stringify(images, null, 2)}
`

fs.mkdirSync(path.dirname(output), { recursive: true })
fs.writeFileSync(output, content)

console.log(`Generated ${path.relative(root, output)}`)
console.log(`Videos: ${videos.length}`)
console.log(`Images: ${images.length}`)
